/*
 *  gen_geometry.js — bake FlubberForge geometry.json into C++ static arrays.
 *
 *  Usage:  node tools/gen_geometry.js <path-to-geometry.json> [out-dir]
 *          (defaults: ../flubberforge/www/geometry.json, src/)
 *
 *  Emits src/geometry_data.h + src/geometry_data.cpp holding the static scene:
 *  24 meshes (baked pos/nrm + indexed strip/fan/triangle parts), 271 instances
 *  (mesh ref + scale + base transform + pos/rot animation-track indices), and the
 *  four keyframe tables (quats/quatSeq, positions/posSeq). The blob, shields, and
 *  camera are procedural/handcoded, and the ending-logo data (logo/tm/brand/
 *  textAnim) is intentionally NOT baked — the screensaver loops before the finish.
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 */
'use strict';
const fs = require('fs');
const path = require('path');

const srcPath = process.argv[2] || path.join(__dirname, '..', '..', 'flubberforge', 'www', 'geometry.json');
const outDir  = process.argv[3] || path.join(__dirname, '..', 'src');

const data = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

// --- float literal formatting: shortest round-trip + valid C++ float suffix ---
function f(x) {
  let s = String(x);
  if (!/[.eE]/.test(s)) s += '.0';
  return s + 'f';
}
function floatRows(arr, perRow) {
  const out = [];
  for (let i = 0; i < arr.length; i += perRow) {
    out.push('  ' + arr.slice(i, i + perRow).map(f).join(', ') + ',');
  }
  return out.join('\n');
}
function intRows(arr, perRow) {
  const out = [];
  for (let i = 0; i < arr.length; i += perRow) {
    out.push('  ' + arr.slice(i, i + perRow).join(', ') + ',');
  }
  return out.join('\n');
}
const PRIM = { strip: 0, fan: 1, triangles: 2 };

// ---------------------------------------------------------------- cpp body ----
const cpp = [];
cpp.push('/* AUTO-GENERATED by tools/gen_geometry.js from geometry.json — do not edit. */');
cpp.push('#include "geometry_data.h"');
cpp.push('');

// meshes: pos / nrm / per-part index arrays
data.meshes.forEach((m, mi) => {
  cpp.push(`static const float g_mesh${mi}_pos[] = {`);
  cpp.push(floatRows(m.pos, 9));
  cpp.push('};');
  cpp.push(`static const float g_mesh${mi}_nrm[] = {`);
  cpp.push(floatRows(m.nrm, 9));
  cpp.push('};');
  m.parts.forEach((p, pi) => {
    cpp.push(`static const unsigned short g_mesh${mi}_idx${pi}[] = {`);
    cpp.push(intRows(p.idx, 16));
    cpp.push('};');
  });
  cpp.push(`static const FlubPart g_mesh${mi}_parts[] = {`);
  m.parts.forEach((p, pi) => {
    cpp.push(`  { ${PRIM[p.mode]}, ${p.idx.length}, g_mesh${mi}_idx${pi} },`);
  });
  cpp.push('};');
  cpp.push('');
});

cpp.push('const FlubMesh kFlubMeshes[] = {');
data.meshes.forEach((m, mi) => {
  cpp.push(`  { ${m.pos.length / 3}, g_mesh${mi}_pos, g_mesh${mi}_nrm, ${m.parts.length}, g_mesh${mi}_parts },`);
});
cpp.push('};');
cpp.push(`const int kFlubMeshCount = ${data.meshes.length};`);
cpp.push('');

// instances
cpp.push('const FlubInstance kFlubInstances[] = {');
data.instances.forEach((it) => {
  const s = it.s.map(f).join(', ');
  const m = it.m.map(f).join(', ');
  cpp.push(`  { ${it.mesh}, { ${s} }, { ${m} }, ${it.pos}, ${it.rot} },`);
});
cpp.push('};');
cpp.push(`const int kFlubInstanceCount = ${data.instances.length};`);
cpp.push('');

// quats
cpp.push('const float kFlubQuats[][4] = {');
data.quats.forEach((q) => cpp.push(`  { ${q.map(f).join(', ')} },`));
cpp.push('};');
cpp.push(`const int kFlubQuatCount = ${data.quats.length};`);
cpp.push('');

// quatSeq
const qsLen = data.quatSeq[0].length;
cpp.push(`const unsigned short kFlubQuatSeq[][${qsLen}] = {`);
data.quatSeq.forEach((row) => cpp.push(`  { ${row.join(', ')} },`));
cpp.push('};');
cpp.push(`const int kFlubQuatSeqCount = ${data.quatSeq.length};`);
cpp.push(`const int kFlubQuatSeqLen = ${qsLen};`);
cpp.push('');

// positions
cpp.push('const float kFlubPositions[][3] = {');
data.positions.forEach((p) => cpp.push(`  { ${p.map(f).join(', ')} },`));
cpp.push('};');
cpp.push(`const int kFlubPosCount = ${data.positions.length};`);
cpp.push('');

// posSeq
const psLen = data.posSeq[0].length;
cpp.push(`const unsigned short kFlubPosSeq[][${psLen}] = {`);
data.posSeq.forEach((row) => cpp.push(`  { ${row.join(', ')} },`));
cpp.push('};');
cpp.push(`const int kFlubPosSeqCount = ${data.posSeq.length};`);
cpp.push(`const int kFlubPosSeqLen = ${psLen};`);
cpp.push('');

// ----------------------------------------------------------------- header ----
const h = [];
h.push('/* AUTO-GENERATED by tools/gen_geometry.js from geometry.json — do not edit. */');
h.push('#pragma once');
h.push('');
h.push('// Primitive kind for a mesh part. Matches D3DPT_TRIANGLESTRIP / FAN / LIST intent.');
h.push('enum FlubPrim { FLUB_STRIP = 0, FLUB_FAN = 1, FLUB_TRIS = 2 };');
h.push('');
h.push('struct FlubPart { unsigned short prim; unsigned short count; const unsigned short* idx; };');
h.push('struct FlubMesh { int vertCount; const float* pos; const float* nrm; int partCount; const FlubPart* parts; };');
h.push('// Scene instance: mesh index, per-axis scale, row-major base transform (row 3 = translation),');
h.push('// and pos/rot = index into posSeq/quatSeq animation tracks (-1 = none).');
h.push('struct FlubInstance { int mesh; float s[3]; float m[16]; int pos; int rot; };');
h.push('');
h.push('extern const int kFlubMeshCount;');
h.push('extern const FlubMesh kFlubMeshes[];');
h.push('extern const int kFlubInstanceCount;');
h.push('extern const FlubInstance kFlubInstances[];');
h.push('');
h.push('extern const int kFlubQuatCount;');
h.push('extern const float kFlubQuats[][4];');
h.push('extern const int kFlubQuatSeqCount;');
h.push('extern const int kFlubQuatSeqLen;   // 30');
h.push(`extern const unsigned short kFlubQuatSeq[][${qsLen}];`);
h.push('');
h.push('extern const int kFlubPosCount;');
h.push('extern const float kFlubPositions[][3];');
h.push('extern const int kFlubPosSeqCount;');
h.push('extern const int kFlubPosSeqLen;    // 30');
h.push(`extern const unsigned short kFlubPosSeq[][${psLen}];`);
h.push('');

fs.writeFileSync(path.join(outDir, 'geometry_data.h'), h.join('\n'));
fs.writeFileSync(path.join(outDir, 'geometry_data.cpp'), cpp.join('\n'));

let totV = 0, totI = 0;
data.meshes.forEach((m) => { totV += m.pos.length / 3; m.parts.forEach((p) => totI += p.idx.length); });
console.log(`geometry_data: ${data.meshes.length} meshes (${totV} verts, ${totI} indices), ` +
            `${data.instances.length} instances, ${data.quats.length} quats/${data.quatSeq.length} tracks, ` +
            `${data.positions.length} positions/${data.posSeq.length} tracks`);
