/* AUTO-GENERATED by tools/gen_geometry.js from geometry.json — do not edit. */
#pragma once

// Primitive kind for a mesh part. Matches D3DPT_TRIANGLESTRIP / FAN / LIST intent.
enum FlubPrim { FLUB_STRIP = 0, FLUB_FAN = 1, FLUB_TRIS = 2 };

struct FlubPart { unsigned short prim; unsigned short count; const unsigned short* idx; };
struct FlubMesh { int vertCount; const float* pos; const float* nrm; int partCount; const FlubPart* parts; };
// Scene instance: mesh index, per-axis scale, row-major base transform (row 3 = translation),
// and pos/rot = index into posSeq/quatSeq animation tracks (-1 = none).
struct FlubInstance { int mesh; float s[3]; float m[16]; int pos; int rot; };

extern const int kFlubMeshCount;
extern const FlubMesh kFlubMeshes[];
extern const int kFlubInstanceCount;
extern const FlubInstance kFlubInstances[];

extern const int kFlubQuatCount;
extern const float kFlubQuats[][4];
extern const int kFlubQuatSeqCount;
extern const int kFlubQuatSeqLen;   // 30
extern const unsigned short kFlubQuatSeq[][30];

extern const int kFlubPosCount;
extern const float kFlubPositions[][3];
extern const int kFlubPosSeqCount;
extern const int kFlubPosSeqLen;    // 30
extern const unsigned short kFlubPosSeq[][30];
